# Generated by Django 3.2 on 2021-04-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210427_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
