# Generated by Django 3.2 on 2021-04-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
