# Generated by Django 3.2 on 2021-04-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
    ]
