# Generated by Django 3.2 on 2021-04-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0017_auto_20210427_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='recipe',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
